title: Humza's Blog
description: Blog to showcase and share my knowledge in various topics
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
header_pages:
- index.md
style: dark
